### ISSUE TITLE
Unorganized group

### ISSUE THREAD

**Issue by signo** [DavidCramer/plugin-groups#16]
Please add an "Unorganized" switch when selecting plugins, it will make easier to select plugins that are not already in any group yet. You could also add a "Not in groups" or "Unorganized" group in the Plugins page, to make it easier to select plugins not added to  any group or newly added plugins.

Kudos for the great plugin.

**Comment by DavidCramer** [comment]
@signo - V2.0.6 is out, with the ungrouped option now in.
