### ISSUE TITLE
multisite support

### ISSUE THREAD

**Issue by cfoellmann** [DavidCramer/plugin-groups#4]
I am running trunk (4.3+) and multisite.
Problem is that the created categories are not filtering the list on plugins.php. It doesn't throw any errors or notices :disappointed: 

---

SEE: https://wordpress.org/support/topic/multisite-support-117

**Comment by Desertsnowman** [comment]
sweet! I'll take a look at your PR on it. I have very little experience on multisite, so this is a huge help thanks.

**Comment by cfoellmann** [comment]
I see you merged the PR. It is working for the network-admin but needs some fixing for the individual site admin.
Maybe you should consider https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by Desertsnowman** [comment]
I have been tempted. my current workflow is not the best and I do need to optimize. All in good time.
