### ISSUE TITLE
A better way to display groups

### ISSUE THREAD

**Issue by Radzio1615** [DavidCramer/plugin-groups#8]
Hi! I'm very happy that you are working on the new update! If possible, I would prefer to change the way the group list is displayed.  With many groups, the current list view can be problematic. Maybe you can create a drop down list like "Bulk actions".

![image](https://user-images.githubusercontent.com/40895581/122763948-34a82580-d29f-11eb-944e-66819299a8cd.png)

**Comment by DavidCramer** [comment]
@Radzio1615 - I've released v2 last week, and included this kind of navigation. Thanks for suggestion. It's a great addition.
